AWS_ACCESS_KEY: "AKIAZLO366C27VEDS4P3"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "seestream-bucket-prl"
AWS_REGION: "us-east-1"

SECRET_KEY: 'sk_test_hY1mB76ED9TZikNsUSFaKNrb00Bh8SasKJ'
PUBLISHABLE_KEY: 'pk_test_EDZfXTNdGXuw0GUOcHrd2Ila002bwGZG0J'